### ISSUE TITLE
Non-existing parent folder

### ISSUE THREAD

**Issue by jbriales** [dotphiles/dotsync#13]
Currently `dotsync -L` fails when the parent folder for the link destination doesn't exist.
This, however, may happen sometimes in newly installed systems.
E.g. the folder *$HOME/.config/xfce4/terminal* for the terminal configuration for xfce4, in *$HOME/.config/xfce4/terminal/terminalrc*, doesn't seem to exist until we manually adjust some custom property in the preferences.
So, would it be acceptable to fix this by applying `mkdir -p ...` on the parent path?

**Comment by balrok** [comment]
I think closed by: https://github.com/dotphiles/dotsync/pull/15

**Comment by jbriales** [comment]
It should indeed!
